#!/bin/bash
set -e

script_dir=$(dirname $0)

sudo add-apt-repository -y ppa:hvr/ghc
sudo apt update
sudo apt -y install "exuberant-ctags" "silversearcher-ag" "ack-grep"
sudo apt -y install "curl"
sudo apt -y install "vim"
sudo apt -y install "emacs24"
sudo apt -y install "software-properties-common"
sudo apt -y install "golang-go"
sudo apt -y install "cabal-install-1.22" "ghc-7.10.3"
sudo apt -y install "ruby"
sudo apt -y install "openjdk-8-jdk" "maven" "gradle"

if [[ ! -f /etc/apt/sources.list.d/ ]] ; then
   sudo sh -c 'echo "deb http://www.cs.ox.ac.uk/projects/fdr/downloads/debian/ fdr release\n" > /etc/apt/sources.list.d/fdr.list'
   wget -qO - http://www.cs.ox.ac.uk/projects/fdr/downloads/linux_deploy.key | sudo apt-key add -
   sudo apt-get update
   sudo apt-get install fdr
fi

"${script_dir}/install-common-config-bundles"
