#!/bin/bash
set -e

script_dir=$(dirname $0)

sudo add-apt-repository -y ppa:hvr/ghc
sudo apt update
sudo apt -y install "exuberant-ctags" "silversearcher-ag" "ack-grep"
sudo apt -y install "curl"
sudo apt -y install "vim"
sudo apt -y install "emacs24"
sudo apt -y install "software-properties-common"
sudo apt -y install "golang-go"
sudo apt -y install "cabal-install-1.22" "ghc-7.10.3"
sudo apt -y install "ruby"
sudo apt -y install "openjdk-8-jdk" "maven" "gradle"

"${script_dir}/install-common-config-bundles"
