#!/bin/bash
set -e

script_dir=$(dirname $0)

ls "${HOME}/.vim" > /dev/null 2> /dev/null || curl vimfiles.luan.sh/install | bash

ls "${HOME}/.emacs.d" > /dev/null 2> /dev/null || git clone git://github.com/bbatsov/prelude.git "${HOME}/.emacs.d"
ls "${HOME}/.emacs.d/prelude-modules.el" > /dev/null 2> /dev/null || cp "${script_dir}/emacs-prelude-modules.el" "${HOME}/.emacs.d/prelude-modules.el"
