#!/bin/bash -eu

main() {
   echo "Installing ubuntu apps..."
   use_ppas
   install_easy_ubuntu_packages
   install_fdr
   install_virtualbox_and_vagrant
   install_bosh2_cli
   echo "Ubuntu apps successfully installed!"
}

use_ppas() {
   for repo in \
      "ppa:hvr/ghc" \
      "ppa:ubuntu-elisp/ppa" \
      "ppa:neovim-ppa/unstable"
   do
      sudo add-apt-repository -y $repo
   done

   sudo apt update
}

install_easy_ubuntu_packages() {
   for app in \
      "exuberant-ctags" "silversearcher-ag" "ack-grep" \
      "curl" \
      "vim" \
      "emacs-snapshot" \
      "software-properties-common" \
      "golang-go" \
      "cabal-install-1.22" "ghc-7.10.3" \
      "build-essential" "ruby" "ruby-dev" "libxml2-dev" \
      "libsqlite3-dev" "libxslt1-dev" "libpq-dev" "libmysqlclient-dev" \
      "zlib1g-dev" \
      "virtualbox" \
      "openjdk-8-jdk" "maven" "gradle" \
      "shellcheck" \
      "vim-nox" \
      "python-dev" "python-pip" "python3-dev" "python3-pip" \
      "neovim"
   do
      sudo apt -y install $app
   done
}

install_fdr() {
   if [[ ! -f /etc/apt/sources.list.d/fdr.list ]] ; then
      sudo sh -c 'echo "deb http://www.cs.ox.ac.uk/projects/fdr/downloads/debian/ fdr release\n" > /etc/apt/sources.list.d/fdr.list'
      wget -qO - http://www.cs.ox.ac.uk/projects/fdr/downloads/linux_deploy.key | sudo apt-key add -
      sudo apt-get update
      sudo apt-get install fdr
   fi
}

install_virtualbox_and_vagrant() {
   if [[ ! -f /etc/apt/sources.list.d/vbox.list ]] ; then
       sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian xenial contrib\n" > /etc/apt/sources.list.d/vbox.list'
       wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
       sudo apt update
       sudo apt -y install virtualbox-5.1 dkms
   fi

   sudo apt -y install vagrant
}

install_bosh2_cli() {
   wget -O "${HOME}/bin/bosh2" https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-0.0.141-linux-amd64
   chmod +x "${HOME}/bin/bosh2"
}

main
